(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ac-delay 1.0)
 '(ag-highlight-search t)
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(ansi-color-names-vector
   ["#eee8d5" "#dc322f" "#859900" "#b58900" "#268bd2" "#d33682" "#2aa198" "#839496"])
 '(auto-save-interval 3000)
 '(bm-cycle-all-buffers t)
 '(bm-highlight-style 'bm-highlight-only-fringe)
 '(compilation-message-face 'default)
 '(counsel-locate-cmd 'counsel-locate-cmd-es)
 '(cua-global-mark-cursor-color "#2aa198")
 '(cua-normal-cursor-color "#657b83")
 '(cua-overwrite-cursor-color "#b58900")
 '(cua-read-only-cursor-color "#859900")
 '(custom-enabled-themes '(adwaita))
 '(custom-safe-themes
   '("a8245b7cc985a0610d71f9852e9f2767ad1b852c2bdea6f4aadc12cce9c4d6d0" "8db4b03b9ae654d4a57804286eb3e332725c84d7cdab38463cb6b97d5762ad26" "31a01668c84d03862a970c471edbd377b2430868eccf5e8a9aec6831f1a0908d" "1297a022df4228b81bc0436230f211bad168a117282c20ddcba2db8c6a200743" "726dd9a188747664fbbff1cd9ab3c29a3f690a7b861f6e6a1c64462b64b306de" "d677ef584c6dfc0697901a44b885cc18e206f05114c8a3b7fde674fce6180879" "8aebf25556399b58091e533e455dd50a6a9cba958cc4ebb0aab175863c25b9a4" "a71be4e5e9e418025daea651f8a1628953abb7af505da5e556e95061b6a6e389" default))
 '(diredp-hide-details-initially-flag nil)
 '(display-time-day-and-date t)
 '(display-time-mode t)
 '(fci-rule-color "#eee8d5")
 '(find-file-suppress-same-file-warnings t)
 '(flyspell-default-dictionary "en_US")
 '(flyspell-issue-message-flag nil)
 '(fortune-dir "d:/rgd/dropbox/etc/fortunes")
 '(fortune-file "")
 '(fortune-program "c:/sys/fortune/fortune.bat")
 '(grep-find-ignored-files
   '(".#*" "*.o" "*~" "*.bin" "*.bak" "*.obj" "*.map" "*.ico" "*.pif" "*.lnk" "*.a" "*.ln" "*.blg" "*.bbl" "*.dll" "*.drv" "*.vxd" "*.386" "*.elc" "*.lof" "*.glo" "*.idx" "*.lot" "*.fmt" "*.tfm" "*.class" "*.fas" "*.lib" "*.mem" "*.x86f" "*.sparcf" "*.dfsl" "*.pfsl" "*.d64fsl" "*.p64fsl" "*.lx64fsl" "*.lx32fsl" "*.dx64fsl" "*.dx32fsl" "*.fx64fsl" "*.fx32fsl" "*.sx64fsl" "*.sx32fsl" "*.wx64fsl" "*.wx32fsl" "*.fasl" "*.ufsl" "*.fsl" "*.dxl" "*.lo" "*.la" "*.gmo" "*.mo" "*.toc" "*.aux" "*.cp" "*.fn" "*.ky" "*.pg" "*.tp" "*.vr" "*.cps" "*.fns" "*.kys" "*.pgs" "*.tps" "*.vrs" "*.pyc" "*.pyo" "*.ilk" "*.pch" "*.ocx" "*.exp" "*.pdb" "*.tlb" "*.exe" "*.iobj" "*.idb"))
 '(highlight-changes-colors '("#d33682" "#6c71c4"))
 '(highlight-symbol-colors
   (--map
	(solarized-color-blend it "#fdf6e3" 0.25)
	'("#b58900" "#2aa198" "#dc322f" "#6c71c4" "#859900" "#cb4b16" "#268bd2")))
 '(highlight-symbol-foreground-color "#586e75")
 '(highlight-tail-colors
   '(("#eee8d5" . 0)
	 ("#B4C342" . 20)
	 ("#69CABF" . 30)
	 ("#69B7F0" . 50)
	 ("#DEB542" . 60)
	 ("#F2804F" . 70)
	 ("#F771AC" . 85)
	 ("#eee8d5" . 100)))
 '(hl-bg-colors
   '("#DEB542" "#F2804F" "#FF6E64" "#F771AC" "#9EA0E5" "#69B7F0" "#69CABF" "#B4C342"))
 '(hl-fg-colors
   '("#fdf6e3" "#fdf6e3" "#fdf6e3" "#fdf6e3" "#fdf6e3" "#fdf6e3" "#fdf6e3" "#fdf6e3"))
 '(image-dired-external-viewer "imdisplay.exe")
 '(inhibit-startup-screen t)
 '(line-number-mode nil)
 '(locate-command "d:/rgd/dropbox/cmd/locate.cmd")
 '(magit-diff-use-overlays nil)
 '(neo-theme 'classic)
 '(newsticker-url-list
   '(("IndycarToday 24hrs" "https://feeds.feedburner.com/IndyCarToday-popular" nil nil nil)
	 ("GIMP News" "https://www.gimp.org/feeds/atom.xml" nil 604800 nil)
	 ("Weather Beachwood" "http://www.rssweather.com/zipcode/44122/rss.php" nil nil nil)
	 ("Sacha Chua Emacs" "http://sachachua.com/blog/category/emacs/feed" nil nil nil)
	 ("Planet Emacsen" "http://planet.emacsen.org/atom.xml" nil nil nil)
	 ("Reddit Emacs" "https://www.reddit.com/r/emacs/.rss" nil nil nil)
	 ("Reddit Traveller" "https://www.reddit.com/r/traveller/.rss" nil nil nil)
	 ("Reddit Cordcutters" "https://www.reddit.com/r/cordcutters/.rss" nil nil nil)
	 ("CotI" "http://www.travellerrpg.com/CotI/Discuss/external.php?type=RSS2" nil nil nil)
	 ("Armchair Adventurer" "https://armchairadventurerblog.com/category/podcast/feed/" nil nil nil)
	 ("NASA Breaking News" "https://www.nasa.gov/rss/dyn/breaking_news.rss" nil nil nil)
	 ("RPG Site" "https://www.rpgsite.net/feed" nil nil nil)
	 ("EN World 100" "http://www.enworld.org/forum/external.php?do=rss&type=newcontent&sectionid=1&days=120&count=100" nil nil nil)
	 ("RPG.net" "http://www.rpg.net/index.xml" nil nil nil)
	 ("RPGnet Future" "http://www.rpg.net/columns/future/future.xml" nil nil nil)))
 '(org-cycle-separator-lines 1)
 '(org-dropbox-datetree-file "")
 '(org-dropbox-note-dir "")
 '(org-link-frame-setup
   '((vm . vm-visit-folder-other-frame)
	 (vm-imap . vm-visit-imap-folder-other-frame)
	 (gnus . org-gnus-no-new-news)
	 (file . find-file)
	 (wl . wl-other-frame)))
 '(org-log-refile 'time)
 '(org-refile-allow-creating-parent-nodes 'confirm)
 '(org-refile-targets '((org-agenda-files :maxlevel . 6) (nil :level . 1)))
 '(org-refile-use-outline-path 'file)
 '(org-return-follows-link t)
 '(org-trello-current-prefix-keybinding "C-c o")
 '(package-archives
   '(("gnu" . "http://elpa.gnu.org/packages/")
	 ("melpa" . "http://melpa.org/packages/")))
 '(package-selected-packages
   '(magit sunshine ivy-rich smex browse-kill-ring bm ivy-posframe use-package projectile ivy swiper fzf avy system-packages projectile-speedbar org-bullets names mode-icons ivy-todo ivy-hydra git-commit fortune-cookie flyspell-correct dropbox counsel async ivy-xref imenu-anywhere hydra org-dropbox esup dashboard page-break-lines counsel-projectile dired-sort-menu+ dired-sort-menu w32-browser dired+ flyspell-correct-ivy powerline sr-speedbar font-lock+ free-keys neotree counsel-gtags edit-server pkg-info org))
 '(paradox-github-token t)
 '(pos-tip-background-color "#eee8d5")
 '(pos-tip-foreground-color "#586e75")
 '(powerline-default-separator 'utf-8)
 '(projectile-completion-system 'ivy)
 '(projectile-project-root-files
   '("rebar.config" "project.clj" "build.boot" "SConstruct" "pom.xml" "build.sbt" "gradlew" "build.gradle" ".ensime" "Gemfile" "requirements.txt" "setup.py" "tox.ini" "gulpfile.js" "Gruntfile.js" "bower.json" "composer.json" "Cargo.toml" "mix.exs" "stack.yaml" "info.rkt" "DESCRIPTION" "TAGS" "GTAGS" "sla.projectile"))
 '(safe-local-variable-values '((eval load-file org-conf-el)))
 '(show-paren-mode t)
 '(smartrep-mode-line-active-bg (solarized-color-blend "#859900" "#eee8d5" 0.2))
 '(tab-width 4)
 '(tabbar-background-color "gray90")
 '(tabbar-ruler-fancy-close-image t)
 '(tabbar-ruler-fancy-current-tab-separator 'roundstub)
 '(tabbar-ruler-fancy-tab-separator nil)
 '(tabbar-ruler-modified-symbol t)
 '(tabbar-ruler-movement-timer-delay 2.0)
 '(tabbar-ruler-popup-menu nil)
 '(tabbar-ruler-popup-scrollbar nil)
 '(tabbar-ruler-popup-toolbar nil)
 '(tabbar-ruler-swap-faces t)
 '(tabbar-ruler-tab-height 20)
 '(tabbar-ruler-tab-padding 2)
 '(tabbar-separator '(0.5))
 '(term-default-bg-color "#fdf6e3")
 '(term-default-fg-color "#657b83")
 '(tool-bar-mode nil)
 '(tooltip-mode nil)
 '(url-proxy-services nil)
 '(vc-annotate-background nil)
 '(vc-annotate-color-map
   '((20 . "#dc322f")
	 (40 . "#c85d17")
	 (60 . "#be730b")
	 (80 . "#b58900")
	 (100 . "#a58e00")
	 (120 . "#9d9100")
	 (140 . "#959300")
	 (160 . "#8d9600")
	 (180 . "#859900")
	 (200 . "#669b32")
	 (220 . "#579d4c")
	 (240 . "#489e65")
	 (260 . "#399f7e")
	 (280 . "#2aa198")
	 (300 . "#2898af")
	 (320 . "#2793ba")
	 (340 . "#268fc6")
	 (360 . "#268bd2")))
 '(vc-annotate-very-old-color nil)
 '(weechat-color-list
   '(unspecified "#fdf6e3" "#eee8d5" "#990A1B" "#dc322f" "#546E00" "#859900" "#7B6000" "#b58900" "#00629D" "#268bd2" "#93115C" "#d33682" "#00736F" "#2aa198" "#657b83" "#839496"))
 '(wttrin-default-accept-language '("Accept-Language" . "en-US,en;q=0.8")))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(Info-quoted ((t (:inherit fixed-pitch-serif :foreground "steel blue"))))
 '(diredp-dir-priv ((t (:foreground "DarkRed"))))
 '(diredp-exec-priv ((t (:foreground "green"))))
 '(diredp-read-priv ((t (:foreground "red"))))
 '(diredp-write-priv ((t (:foreground "purple"))))
 '(ivy-posframe ((t (:inherit default :background "light gray" :foreground "black"))))
 '(org-meta-line ((t (:inherit font-lock-comment-face :height 0.8))))
 '(powerline-active0 ((t (:background "SteelBlue1" :foreground "black"))))
 '(powerline-active1 ((t (:inherit mode-line :background "SteelBlue3" :foreground "black"))))
 '(powerline-active2 ((t (:inherit mode-line :background "SteelBlue4" :foreground "white"))))
 '(powerline-inactive0 ((t (:inherit mode-line-inactive :background "Grey60" :foreground "black"))))
 '(powerline-inactive1 ((t (:inherit mode-line-inactive :background "Grey50" :foreground "black"))))
 '(powerline-inactive2 ((t (:inherit mode-line-inactive :background "Grey25" :foreground "white"))))
 '(tabbar-button ((t (:inherit tabbar-default :box nil :height 120 :width normal :foundry "outline" :family "Lucida Console"))))
 '(tabbar-default ((t (:background "ghost white" :foreground "#2E3436" :box (:line-width -1 :style released-button)))))
 '(tabbar-highlight ((t (:background "gray95" :foreground "gray5" :box (:line-width 5 :color "white") :underline nil))))
 '(tabbar-key-binding ((t (:foreground "black"))))
 '(tabbar-selected ((t (:inherit nil :stipple nil :background "white" :foreground "#2E3436" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "outline" :family "Lucida Console"))))
 '(tabbar-selected-modified ((t (:inherit tabbar-default :background "white" :foreground "red" :box nil :height 120 :width normal :foundry "outline" :family "Lucida Console"))))
 '(tabbar-separator ((t (:inherit tabbar-default :background "ghost white" :height 0.6))))
 '(tabbar-unselected ((t (:inherit nil :stipple nil :background "gray95" :foreground "gray5" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "outline" :family "Lucida Console"))))
 '(tabbar-unselected-modified ((t (:inherit tabbar-unselected :foreground "DarkOrange3" :box nil :weight bold :height 120 :width normal :foundry "outline" :family "Lucida Console")))))
